# Site settings
title: Pierre Beucher - Crafteo
subtitle: DevOps Consultant & Trainer
email: pierre@crafteo.io
url: https://crafteo.io
description: "Pierre Beucher - DevOps Consultant & Trainer"
keywords: "devops, kubernetes, cloud, docker"
meta_author: Pierre Beucher

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#¬†- static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: ""

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00d4c4
  primary-rgb: "64,0,163"
  secondary: 4000a3
  secondary-dark: 33007f

# Footer settings
footer:
  copyright: Pierre Beucher - Crafteo
  location: Where am I located?
  social: A few social links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    name: Stack Overflow
    url: https://stackoverflow.com/users/5465973/pierre-b
  - title: github
    name: GitHub
    url: https://github.com/PierreBeucher
  - title: linkedin
    url: https://www.linkedin.com/in/pierre-beucher/
    name: LinkedIn

# Postal address (add as many lines as necessary)
address:
  - line: üìç üó∫Ô∏è Lyon, France
  - line: üöÑ Mobile through all of France

# Credits content
credits:
- line: 'Graphic identity made with <3 by'
- line: '<a href="https://www.lesalfredines.com/">Les Alfredines</a>'
- line:
- line: 'Page theme adapted from'
- line: '<a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer of Jerome Lachaud</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
