# Site settings
title: Crafteo - Formation & Expertise DevOps
subtitle: Formation & Expertise DevOps
email: pierre@crafteo.io
url: https://crafteo.io
description: "Crafteo - Formation Devops par la pratique!"
keywords: "devops, docker"
meta_author: Pierre Beucher

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: ""

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00d4c4
  primary-rgb: "64,0,163"
  secondary: 4000a3
  secondary-dark: 33007f

# Footer settings
footer:
  copyright: Pierre Beucher - Crafteo
  location: Ou me trouver?
  social: Retrouvez-moi aussi sur...
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://stackoverflow.com/users/5465973/pierre-b
  - title: github
    url: https://github.com/PierreBeucher
  - title: linkedin
    url: https://www.linkedin.com/in/pierre-beucher/

# Postal address (add as many lines as necessary)
address:
  - line: "Un peu partout dans les Cordées lyonnaises, mais surtout ici:"
  - line:
  - line: Crafteo
  - line: 13 cours de Verdun Gensoul
  - line: 69002 Lyon

# Credits content
credits:
- line: 'Design graphique fait avec <3 par'
- line: '<a href="https://www.lesalfredines.com/">Les Alfredines</a>'
- line:
- line: 'Mise en page adapté du theme'
- line: '<a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer de Jerome Lachaud</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
